image: gcc

build:
  stage: build
  tags:
    - docker
  script:
    - make
  artifacts:
    paths:
      - sint

# run tests using the binary built before
test:
  stage: test
  tags:
    - docker
  before_script:
    - apt-get update; sudo apt-get -y install expect
  script:
    - ./runtest
